# ------------------------------------------------------------
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
# ------------------------------------------------------------

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: receivemediapost
  namespace: longhaul-test
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: dapr-redis-master.dapr-components.svc.cluster.local:6379
  - name: redisPassword
    secretKeyRef:
      name: dapr-redis
      key: redis-password
auth:
  secretStore: kubernetes
