kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: secret-access-role-account-binding
 namespace: longhaul-test
subjects:
- kind: ServiceAccount
  name: default
  namespace: longhaul-test
roleRef:
 kind: Role
 name: secret-access-role
 apiGroup: rbac.authorization.k8s.io