# ------------------------------------------------------------
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
# ------------------------------------------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashtag-actor-app
  labels:
    app: hashtag-actor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashtag-actor
  template:
    metadata:
      labels:
        app: hashtag-actor
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "hashtag-actor"
        dapr.io/port: "3000"
        dapr.io/log-as-json: "true"
    spec:
      containers:
      - name: hashtag-actor
        image: dapriotest/hashtag-app:dev
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: hashtag-actor.dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashtag-counter-app
  labels:
    app: hashtag-counter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashtag-counter
  template:
    metadata:
      labels:
        app: hashtag-counter
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "hashtag-counter"
        dapr.io/port: "3000"
        dapr.io/log-as-json: "true"
    spec:
      containers:
      - name: hashtag-counter
        image: dapriotest/hashtag-app:dev
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: hashtag-counter.dev